[default]
db_path = "zec-wallet.db"
confirmations = 6
lwd_url = "https://zec.rocks"
notify_tx_url = "http://btcpayserver:9000/zcashlikedaemoncallback/tx?cryptoCode=zec&hash="
poll_interval = 60
regtest = false
orchard = true

[debug]
address = "127.0.0.1"

[release]
address = "0.0.0.0"
