[global]
db_path = "zec-wallet-test.db"
confirmations = 6
lwd_url = "https://testnet.zec.rocks"
notify_tx_url = "http://btcpayserver:9000/zcashlikedaemoncallback/tx?cryptoCode=zec&hash="
poll_interval = 60
regtest = true

[debug]
address = "127.0.0.1"

[release]
address = "0.0.0.0"
