name: Build and Release on MacOS

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  build-macos:
    if: "!contains(github.head_ref, 'release-please--')"
    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: oras-project/setup-oras@v1
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Pull zcashd package
        run: |
          echo $GHCR_PASSWORD | oras login ghcr.io -u hhanh00 --password-stdin
          oras pull ghcr.io/hhanh00/zcashd:6.3.0
          tar xvzf zcashd.tar.gz
          echo "$PWD/zcashd" >> $GITHUB_PATH
        env:
          GHCR_PASSWORD: ${{ secrets.GHCR_PASSWORD }}
      - name: Setup regtest
        run: |
          pushd zcashd
          mkdir regtest
          cp zcash.conf regtest/
          $GITHUB_WORKSPACE/docs/setup-regtest.sh
          lightwalletd --no-tls-very-insecure --zcash-conf-path regtest/zcash.conf --data-dir regtest --grpc-bind-addr 0.0.0.0:9067 --log-file /dev/stdout &
          popd
      - name: Build
        run: cargo build
      - name: Run
        env:
          RUST_LOG: info
        run: |
          cp sample.env .env
          ./target/debug/zcash-walletd &
      - name: Tests
        run: |
          pushd test
          pnpm i
          pnpm test
